<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
    <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/jquery.fancybox.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>


    <?php echo $this->content; ?>

<?php echo $this->inlineScript()
    ->offsetSetFile(100, $this->basePath() . '/js/jquery.min.js')
    ->offsetSetFile(300, $this->basePath() . '/js/plugins.js')
    ->offsetSetFile(500, $this->basePath() . '/js/login.js')
; ?>
    </body>
</html>