<?php
$form = new Zend\Form\Form();
$form->setAttribute('action',  $this->url('genericModel', array('action' => 'delete-multiple', 'model' => $model)));
$form->setAttribute('method', 'post');
?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Manage ' . $model) ?></h3>
        </div>
        <div class="panel-body">
            <?php if (count($relationFilters)) : ?>
                <?php $relationFilters->prepare(); ?>
                <?php echo $this->form()->openTag($relationFilters); ?>
                <?php echo $this->translate('Filter by:'); ?>
                <?php foreach ($relationFilters as $element) : ?>
                    <div class="form-group">
                        <?php echo $this->translate($element->getLabel()) ; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formElement($element); ?>
                    </div>
                <?php endforeach; ?>
                    <div class="form-group">
                        <button type="submit" name="Filter" class="btn btn-success btn-sm">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
                <div class="clearfix"></div>
            <?php endif; ?>

            <?php $form->prepare(); ?>
            <?php echo $this->form()->openTag($form); ?>
            <table class="table  table-striped" width="100%">
                <thead>
                    <tr>
                        <td class="text-center" width="2%">#</td>
                        <?php foreach ($visibleListingFields as $field) : ?>
                            <td><?php echo $this->translate($field) ?></td>
                        <?php endforeach; ?>
                        <?php foreach ($listingSwitches as $switch) : ?>
                            <td><?php echo $this->translate($switch) ?></td>
                        <?php endforeach; ?>
                        <td class="text-center">&nbsp;</td>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($listing as $item ) : ?>
                    <tr>
                        <td class="text-center"><input type="checkbox" name="multipleDeleteCheck[]" value="<?php echo $item->id ?>"/></td>
                        <?php foreach ($visibleListingFields as $field) : ?>
                            <?php if (isset($item->childCount) && (int)$item->childCount > 0): ?>
                                <td><a href="<?php echo $this->url('genericModel', array('model' => $model, 'parent' => $this->escapeHtml($item->id) )); ?>" ><?php echo $this->escapeHtml($item->$field); ?></a></td>
                            <?php else: ?>
                                <td><a href="<?php echo $this->url('genericModel', array('action' => 'edit', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>" ><?php echo $this->escapeHtml($item->$field); ?></a></td>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php foreach ($listingSwitches as $switch) : ?>
                            <td><input type="checkbox" class="bootstrapSwitchIndex" data-model="<?php echo $model ?>" data-field="<?php echo $switch ?>" data-id="<?php echo $item->id ?>" name="<?php echo $switch ?>[<?php echo $item->id ?>]" <?php echo ($item->$switch) ? 'checked' : ''; ?>></td>
                        <?php endforeach; ?>
                        <td class="text-center" width="70">
                            <div class="btn-group">
                                <?php if (isset($item->childCount) && (int)$item->childCount > 0): ?>
                                    <a href="<?php echo $this->url('genericModel', array('action' => 'edit', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>" type="button" class="btn btn-xs btn-info">
                                        <span class="glyphicon  glyphicon-pencil"></span>
                                    </a>
                                <?php endif; ?>
                                <a href="<?php echo $this->url('genericModel', array('action' => 'delete', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>" type="button" class="btn btn-xs btn-warning">
                                    <span class="glyphicon  glyphicon-trash"></span>
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="btn-group">
                <a href="<?php echo $this->url('genericModel', array('action' => 'add', 'model' => $model)); ?>" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?php echo $this->translate('Add New'); ?>
                </a>
                <button type="submit" class="btn btn-warning">
                    <span class="glyphicon glyphicon-trash"></span>
                    <?php echo $this->translate('Delete Selected'); ?>
                </button>

            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
