
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
        </div>
        <div class="panel-body">
            <ul class="nav nav-tabs">
                <?php foreach ($form->getTabs() as $key => $tab) : ?>
                <li class="<?php echo ($key == 0)? 'active': '' ?>"><a href="#tab-<?php echo $key; ?>" data-toggle="tab"><?php echo $tab['name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
            <?php $form->getFormObject()->prepare() ?>
            <?php echo $this->form()->openTag($form->getFormObject()); ?>
            <!-- Tab panes -->
            <div class="tab-content">
                <?php foreach ($form->getTabs() as $key => $tab) : ?>
                <div class="tab-pane <?php echo ($key == 0)? 'active': '' ?>" id="tab-<?php echo $key; ?>">
                    <?php foreach ($tab['fields'] as $field) : ?>
                        <?php if (is_array($multilingualFields) && in_array($field , $multilingualFields)) : ?>
                            <?php foreach ($this->controlPanel->getSiteLanguages() as $languageId => $language): ?>
                                <?php echo $form->getFormObject()->get($field . '[' . $languageId . ']')->getLabel() . '( ' . $language['name'] . ' )' ?>
                                <?php echo $this->formElementErrors($form->getFormObject()->get($field . '[' . $languageId . ']')); ?>
                                <?php if (array_key_exists('data-type', $form->getFormObject()->get($field . '[' . $languageId . ']')->getAttributes())) : ?>
                                    <?php $attributesArray = $form->getFormObject()->get($field . '[' . $languageId . ']')->getAttributes(); ?>
                                    <div class="input-group">
                                        <?php echo $this->formElement($form->getFormObject()->get($field . '[' . $languageId . ']')); ?>
                                        <span class="input-group-btn">
                                        <?php if( $form->getFormObject()->get($field . '[' . $languageId . ']')->getValue() != '' && $attributesArray['data-type'] == 'image' ): ?>
                                            <a href="<?php echo $form->getFormObject()->get($field . '[' . $languageId . ']')->getValue() ?>" class="btn btn-default image-preview" type="button">
                                                <span class="glyphicon glyphicon-picture"></span>
                                            </a>
                                        <?php endif;?>
                                            <a href="/filemanager/dialog.php?field_id=<?php echo $attributesArray['id'] ?>&type=<?php echo ($attributesArray['data-type'] == 'image')? '1':'2' ; ?>" class="btn btn-default iframe-btn " type="button">Select</a>
                                        </span>
                                    </div>
                                <?php else: ?>
                                    <?php echo $this->formElement($form->getFormObject()->get($field . '[' . $languageId . ']')); ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php echo $form->getFormObject()->get($field)->getLabel(); ?>
                            <?php echo $this->formElementErrors($form->getFormObject()->get($field)); ?>
                            <?php if (array_key_exists('data-type', $form->getFormObject()->get($field)->getAttributes())) : ?>
                                <?php $attributesArray = $form->getFormObject()->get($field)->getAttributes(); ?>
                                <div class="input-group">
                                <?php echo $this->formElement($form->getFormObject()->get($field)); ?>
                                    <span class="input-group-btn">
                                        <?php if( $form->getFormObject()->get($field)->getValue() != '' && $attributesArray['data-type'] == 'image' ): ?>
                                            <a href="<?php echo $form->getFormObject()->get($field)->getValue() ?>" class="btn btn-default image-preview" type="button">
                                                <span class="glyphicon glyphicon-picture"></span>
                                            </a>
                                        <?php endif;?>
                                        <a href="/filemanager/dialog.php?field_id=<?php echo $attributesArray['id'] ?>&type=<?php echo ($attributesArray['data-type'] == 'image')? '1':'2' ; ?>" class="btn btn-default iframe-btn " type="button">Select</a>
                                    </span>
                                </div>
                            <?php else: ?>
                                <?php echo $this->formElement($form->getFormObject()->get($field)); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
                <?php endforeach; ?>
            </div>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-floppy-disk"></span>Save
            </button>
            <?php echo $this->form()->closeTag($form->getFormObject()); ?>
        </div>
    </div>
