<?php
$form = new Zend\Form\Form();
$form->setAttribute('action',  $this->url('administration', array('action' => 'delete-multiple', 'model' => $model)));
$form->setAttribute('method', 'post');
?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
        </div>
        <div class="panel-body">
            <?php $form->prepare(); ?>
            <?php echo $this->form()->openTag($form); ?>
            <table class="table  table-striped" width="100%">
                <thead>
                    <tr>
                        <td class="text-center" width="2%">#</td>
                        <?php foreach ($visibleListingFields as $field) : ?>
                            <td><?php echo $field ?></td>
                        <?php endforeach; ?>
                        <?php foreach ($listingSwitches as $switch) : ?>
                            <td><?php echo $switch ?></td>
                        <?php endforeach; ?>
                        <td class="text-center">&nbsp;</td>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($listing as $item ) : ?>
                    <tr>
                        <td class="text-center"><input type="checkbox" name="multipleDeleteCheck[]" value="<?php echo $item->id ?>"/></td>
                        <?php foreach ($visibleListingFields as $field) : ?>
                        <td><?php echo $this->escapeHtml($item->$field); ?></td>
                        <?php endforeach; ?>
                        <?php foreach ($listingSwitches as $switch) : ?>
                            <td><?php echo $this->escapeHtml($item->$switch); ?></td>
                        <?php endforeach; ?>
                        <td class="text-center" width="2%">
                            <a href="<?php echo $this->url('administration', array('action' => 'delete', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>" type="button" class="btn btn-xs btn-default">
                                <span class="glyphicon  glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="btn-group">
                <a href="<?php echo $this->url('administration', array('action' => 'add', 'model' => $model)); ?>" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    Add New
                </a>
                <button type="submit" class="btn btn-warning">
                    <span class="glyphicon glyphicon-trash"></span>
                    Delete selected
                </button>

            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
