
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
        </div>
        <div class="panel-body">
            <table class="table  table-striped" width="100%">
                <thead>
                    <tr>
                        <td class="text-center" width="2%">#</td>
                        <?php foreach ($visibleListingFields as $field) : ?>
                            <td><?php echo $field ?></td>
                        <?php endforeach; ?>
                        <?php foreach ($listingSwitches as $switch) : ?>
                            <td><?php echo $switch ?></td>
                        <?php endforeach; ?>
                        <td class="text-center">&nbsp;</td>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($listing as $item ) : ?>
                    <tr>
                        <td class="text-center"><input type="checkbox" name="multipleCheck" value="<?php echo $item->id ?>"/></td>
                        <?php foreach ($visibleListingFields as $field) : ?>
                        <td><?php echo $item->$field ?></td>
                        <?php endforeach; ?>
                        <?php foreach ($listingSwitches as $switch) : ?>
                            <td><?php echo $item->$switch ?></td>
                        <?php endforeach; ?>
                        <td class="text-center" width="2%">
                            <a href="" type="button" class="btn btn-sm btn-default">
                                <span class="glyphicon  glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
